spring.application.name=backend

frontend.url=http://localhost:3000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/project_management
spring.datasource.username=postgres
spring.datasource.password=caue123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration
jwt.secret=rAcV54bUQ731LFfkPw5WZ9jXmK2nPqRsTuVwYzAb
jwt.expiration=86400000
jwt.cookie.name=pm.auth
jwt.cookie.expiration=86400

# OAuth2 Configuration (desativado até implementar)
# spring.security.oauth2.client.registration.google.client-id=your-google-client-id
# spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
# spring.security.oauth2.client.registration.google.scope=profile,email